### ISSUE TITLE
To Do / In Progress / Done columns template:

### ISSUE THREAD

**Issue by PauGalopa** [PauGalopa/Cpp-SDL2-App#1]
Task: Plan / Implement / Define etc...

What: Class / Function / Structure

Is dependent of: Nothing / example.cc

Who: All / Guille / Arnau / Pau

Time/deadline: In 3 days / by monday / etc..

**Comment by Nyrlem** [comment]
Task: Funcio detectar entrada?
Is dependent of: De com es pilla el input, si es amb cin o un altre
Who: Nose, Guille?
Time: Nose?
